### PR TITLE
Update product_detail_view.js

### LINKED ISSUE #55: set selectedProductId right after rendering so addToCart works

### PR DESCRIPTION
**Pull request by Schrank**
Fixes #55

Set selectedProductId, before add to cart doesn't work

### CODE REVIEW

**Comment by Schrank** [comment]
Might be a problem for configurable - test

**Comment by Vinai** [comment]
Can you add a description what the issue looked like please? Was it that if the add-to-cart button was clicked without a selected option some error occurred? I'm not sure based on the code change.

**Comment by Schrank** [comment]
The addToCart button has a[ click event handler](https://github.com/lizards-and-pumpkins/sample-project/pull/56/commits/53abac6b11efcf202cccbb3cdbef8afa055ee331#diff-0c0c28733da80a76316c2e153d71675cR149)

If `selectedProductId` is not set, the url containts "undefined" - and doesn't work

**Comment by tim-bezhashvyly** [comment]
Does it still work with configurable products?

**Comment by tim-bezhashvyly** [comment]
I checked it and even as it is logically wrong (for the configurable product the ID of a parent product will be initially assigned to this variable) this will do no harm as by the time "Add to Cart" button will be released the variable will be set to selected child product.

**Pull request merged**
