### PR TITLE
Issue #85: Bump required "catalog" version to 0.17.0

### LINKED ISSUE #85: Bump required "catalog" version to 0.17.0

### PR DESCRIPTION
**Pull request by tim-bezhashvyly**
Closes #85, #82.

### CODE REVIEW

**Comment by Vinai** [comment]
Are we already checking out the tagged version in the dev-vm?
If not, lets change that there first before we merge this one.

**Comment by tim-bezhashvyly** [comment]
Yes we are. See https://github.com/lizards-and-pumpkins/sample-project/releases

**Comment by Vinai** [comment]
No we are not, we are so far checking out the master.

**Comment by Vinai** [comment]
https://github.com/lizards-and-pumpkins/dev-vm/pull/62 is merged so we have a release process for the dev-vm, now I'm happy to merge this one.

**Pull request merged**
